language: node_js
node_js:
  - node
dist: trusty
services:
  - mongodb
sudo: false
before_install:
  - openssl aes-256-cbc -K $encrypted_695afc2efa18_key -iv $encrypted_695afc2efa18_iv
    -in functions/service-account.json.enc -out functions/service-account.json -d
  - openssl aes-256-cbc -K $encrypted_695afc2efa18_key -iv $encrypted_695afc2efa18_iv
    -in bin/service-account.json.enc -out bin/service-account.json -d
install: npm install
before_script: node bin/firestore-to-mongo.js
script:
  - npm run generate
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - gh-pages
notifications:
  webhooks: http://webhook.hakatashi.com/travis
before_deploy:
  - cd functions && npm install && cd -
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: LSS6x67O6IaVofB7Qy9r41/eUQgSBNOPTXQ/okWFK6JsUXifJmX3HnXTvaeiIvcNAriZfJAs5htU8JnRHgj3HS8/NHn1QlzRnlyJ1yhRIQtoQJgIwdemWX78r/VlTNrNdKK7mRcyuzZNVkoI0wXnlwN9nY0AOm+3/q7vloWQyNkD6cRWr3TYEouJTzIE/eDU2gaTPQ+gubl9q6d5r39T+hX5VB9l2gOx3KVc3EjOvKMxItanXKlmdMYw2Wjogw1QG3RyQB2BdEwiHkq0enR4kRJpcGrceRg0afk1006yFocl0PPfAVOgU7CIJp+ALqnhCjTFq/JpvtCgSWtTHqVSb97H9QIyT0IoMxdx/qBURGc25YFBHpzR8dlLgJ0oKS91iS+lwdpspVxNea9CIVUZM+c0J0kqhIgYyaBMA4a21y91qlNlL/hK8utP8wAlojTY90G8wi5zwVgqsigr8luctVIIzvbRbgjG3MCetqMr15QfcjlfF8KwEYkTogNJKEBK46zsuJzWxu/5m+/DHmpf4QWJszJ/vk2THLOUi4FoFIdAhmJ9KJjTL8OZ8GHmxs5cfZviv03WPlZmqINYBWQ7NE4/eGKeAG2StZBrIzFLF+cHQq/7FEbFJRps5C5174OAntvckIy2aDbxFb7i4Wlg1GGmiuScRBX7FKtAhhvqCt4=
